AWAITING_DEPLOYMENT_STATUS = "Awaiting Dispatch"
LEGACY_AWAITING_DEPLOYMENT_STATUS = "Awaiting Deployment"
ASSIGNED_STATUS = "Assigned"
TRAVELLING_STATUS = "Travelling"
ON_SITE_STATUS = "On Site"
COMPLETED_STATUS = "Completed"

DAY_ACTIVE_STATUS = "Active"
DAY_CLOSED_STATUS = "Closed"
